version: '3'
services:
    web:
      build:
        context: .
        dockerfile: Dockerfile.dev
      ports:
        - "3000:3000"
      volumes:
        # - /app/node_modules if the current container don't have node_modules -> use this volume config
        - .:/app
    tests:
      build:
        context: .
        dockerfile: Dockerfile.dev
      volumes:
        # - /app/node_modules if the current container don't have node_modules -> use this volume config
        - .:/app
      command: ["npm", "run", "test"]

